version: "3.9"
services:
  app1:
    build: .
    restart:
      on-failure
    environment:
      - NAME_APP=app1
    volumes:
      - ./upload-files:/upload-files
    deploy:
      mode: replicated
      replicas: 4

  proxy:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
